wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.1
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.2
    start_time: 1659980582.240917
    t:
      1:
      - 1
      - 3
      - 55
      2:
      - 1
      - 3
      - 55
      3:
      - 1
      - 13
      - 23
      4: 3.9.2
      5: 0.13.1
      8:
      - 3
      - 5
